### ISSUE TITLE
Add info on co-organizer Science Centre

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2017.fossasia.org#11]
A section for the science centre and additional info

**Comment by raw-at** [comment]
Hi sir it want to contribute in this .I am  trying to be part of open source community by contributing something. I want to do  this.

**Comment by mariobehling** [comment]
This is already resolved. Happy to get contributions. Please join us on slack, if you have any questions: https://fossasia.slack.com Invite link is here: http://fossasia-slack.herokuapp.com
