### ISSUE TITLE
Issue in clonning the project..

### ISSUE THREAD

**Issue by singhjp006** [fossasia/2017.fossasia.org#2]
I have cloned this project using this link https://github.com/fossasia/2017.fossasia.org.git and the code I got on my PC is for 2016. This is the problem.
![screenshot from 2016-07-12 13-48-48](https://cloud.githubusercontent.com/assets/17426705/16760001/68049b72-4837-11e6-8463-c07a3e7a0e66.png)

**Comment by mariobehling** [comment]
It is because we re-used the 2016 site and just updated it to 2017. We need to change a few more things. Thanks for looking at it, but this is not a focus right now.
