### ISSUE TITLE
Add More Speakers Button

### ISSUE THREAD

**Issue by hpdang** [fossasia/2017.fossasia.org#36]
At the end of Featured Speakers, add **More Speakers** button/tab and link to http://2017.fossasia.org/tickets  where they can see all the speakers.

**Comment by sreejakshetty** [comment]
Added the button. Please review it
![screenshot from 2017-02-21 21 19 12](https://cloud.githubusercontent.com/assets/14835922/23172274/474550b2-f87b-11e6-8e0b-c58fd5498817.png)

**Comment by hpdang** [comment]
maybe put the button to the far left

**Comment by hpdang** [comment]
sorry I mean move to the far right, Could you please change it @kamishettysreeja25
