### ISSUE TITLE
Correct Speakers Profile Links 

### ISSUE THREAD

**Issue by hpdang** [fossasia/2017.fossasia.org#37]
some of the Github/Twitter/Linkedin links of the featured speakers on the homepage are incorrect

[FOSSASIA Summit 2017 - Featured Speakers.csv.zip](https://github.com/fossasia/2017.fossasia.org/files/788344/FOSSASIA.Summit.2017.-.Featured.Speakers.csv.zip)

**Comment by the-dagger** [comment]
Some of the links are either missing or wrong.
Please try to go through them and update them wherever applicable.

@brainbreaker  : Linkedin
@mayank408 : Twitter
@betterclever : Personal website (wherever applicable)

https://github.com/fossasia/2017.fossasia.org/blob/gh-pages/index.html

P.S. make sure that there are no merge conflicts ✌️

**Comment by mariobehling** [comment]
And there are also Github links.

**Comment by the-dagger** [comment]
@heysadboy : Github

**Comment by betterclever** [comment]
@mariobehling In a case, a speaker does not have a profile website should I remove that website link field for him/her or enter organization's website instead?

**Comment by the-dagger** [comment]
@betterclever I think that you can remove the website field in such a case. 👍

**Comment by scandindian** [comment]
@the-dagger Sending pull request here https://github.com/fossasia/2017.fossasia.org/pull/40 . I removed the ones that were not there in sheet and corrected remaining.

**Comment by mariobehling** [comment]
@the-dagger @betterclever Actually best would be to link to the speakers project site, if they do not have a personal site.

**Comment by betterclever** [comment]
@heysadboy  There are still some wrong links for github. I observed them while correcting site links. Please have a look after my PR merge once.

**Comment by scandindian** [comment]
@betterclever Thanks, I'll see again.

**Comment by mariobehling** [comment]
Please take out links to "asksusi.com" and delete duplicate code, e.g. of Maxia.

![screenshot from 2017-02-21 23-06-51](https://cloud.githubusercontent.com/assets/1583873/23170560/8f56c02a-f88a-11e6-8f03-68e434512e08.png)

**Comment by duttaditya18** [comment]
This is fixed.

**Comment by nzec** [comment]
This is fixed.
