### ISSUE TITLE
Make Google Cloud logo bigger

### ISSUE THREAD

**Issue by hpdang** [fossasia/2017.fossasia.org#45]
Google Cloud logo is too small compared to others, please make it bigger

**Comment by kamishettysreeja25** [comment]
**Google Cloud** Image is changed to **Google** Image in the repo.
https://github.com/fossasia/2017.fossasia.org/blob/gh-pages/img/google.png
![screenshot from 2017-02-21 23 13 06](https://cloud.githubusercontent.com/assets/14835922/23176951/2a1a4622-f88b-11e6-9e11-eacc8fd960bc.png)

**Comment by mariobehling** [comment]
The goal is to increase the size of the Google Cloud logo which is currently showing on the site.

**Comment by kamishettysreeja25** [comment]
Its currently showing google image on the site 
http://2017.fossasia.org/

**Comment by mariobehling** [comment]
Ok, we can discuss this in detail: We need a big cloud logo on the page. Any other discussion is just eating up time.

**Comment by Aniket965** [comment]
i fixed this bug now it looks better

**Comment by Aniket965** [comment]
![](https://github.com/Aniket965/blueflame/blob/master/sfd.PNG?raw=true)

**Comment by Aniket965** [comment]
created pull request with name of sixed issue #45

**Comment by Aniket965** [comment]
should i changed something in it ?
