### ISSUE TITLE
Add GitHub icon in footer and sidebar

### ISSUE THREAD

**Issue by singhksandeep25** [fossasia/2017.fossasia.org#8]
I suggest adding Github icon : 
1. To the sidebar, replacing dribble icon as it just redirects to fossaia.org
2. To the footer
![page-shot-2016-10-2-fossasia 2017](https://cloud.githubusercontent.com/assets/14184381/19017127/63ebd0e0-884d-11e6-9766-fb9da4e82be8.png)

Also, this issue (https://github.com/fossasia/fossasia.org/issues/66)  exists here too:
![page-shot-2016-10-2-fossasia 2017 1](https://cloud.githubusercontent.com/assets/14184381/19017151/a4b3f5da-884d-11e6-8649-123e7196a2d7.png)

**Comment by jigyasa-grover** [comment]
@sandmanx Yeah, follow as was done for fossasia.org.
